export enum PubSubChannel {
    IS_EDIT_ALLOWCATION_DONE = "IS_EDIT_ALLOWCATION_DONE",
    ACTIVITY_TOGGLE_VIOLATION = "ACTIVITY_TOGGLE_VIOLATION",
    OPEN_CONFIRMATION_MODAL = 'OPEN_CONFIRMATION_MODAL',
    CHANGE_MODE_VIEW = 'CHANGE_MODE_VIEW',
    ON_TODAY = 'ON_TODAY',
    NEXT_PREV_CALENDAR = 'NEXT_PREV_CALENDAR',
    EDIT_SCHEME = 'EDIT_SCHEME',
    EDIT_CRON_TASK = 'EDIT_CRON_TASK',
    EDIT_HOLIDAY = 'EDIT_HOLIDAY',
    SHOW_MODAL_PENDING_REQUEST = 'SHOW_MODAL_PENDING_REQUEST',
    TRIGGER_FETCH_DATA_CALENDAR_PLAN = 'TRIGGER_FETCH_DATA_CALENDAR_PLAN',
}

export const BackgroundColorMonths = [
    "#E0E0E0",
    "#FFFFFF",
    "#E0E0E0",
    "#FFFFFF",
    "#E0E0E0",
    "#FFFFFF",
    "#E0E0E0",
    "#FFFFFF",
    "#E0E0E0",
    "#FFFFFF",
    "#E0E0E0",
    "#FFFFFF",
]

export const PopularTimeZones = [
    { "value": "Pacific/Midway", "label": "(GMT-11) Midway Island" },
    { "value": "Pacific/Niue", "label": "(GMT-11) Alofi, Niue" },
    { "value": "Pacific/Pago_Pago", "label": "(GMT-11) Pago Pago, American Samoa" },
    { "value": "Pacific/Honolulu", "label": "(GMT-10) Honolulu, Hawaii, USA" },
    { "value": "Pacific/Tahiti", "label": "(GMT-10) Tahiti, French Polynesia" },
    { "value": "America/Los_Angeles", "label": "(GMT-07) Los Angeles, USA" },
    { "value": "America/Denver", "label": "(GMT-06) Denver, USA" },
    { "value": "America/Chicago", "label": "(GMT-05) Chicago, USA" },
    { "value": "America/Mexico_City", "label": "(GMT-06) Mexico City, Mexico" },
    { "value": "America/New_York", "label": "(GMT-04) New York, USA" },
    { "value": "America/Toronto", "label": "(GMT-04) Toronto, Canada" },
    { "value": "America/Sao_Paulo", "label": "(GMT-03) Sao Paulo, Brazil" },
    { "value": "Etc/UTC", "label": "(GMT+00) UTC (Coordinated Universal Time)" },
    { "value": "Europe/London", "label": "(GMT+01) London, United Kingdom" },
    { "value": "Africa/Johannesburg", "label": "(GMT+02) Johannesburg, South Africa" },
    { "value": "Europe/Paris", "label": "(GMT+02) Paris, France" },
    { "value": "Europe/Berlin", "label": "(GMT+02) Berlin, Germany" },
    { "value": "Europe/Rome", "label": "(GMT+02) Rome, Italy" },
    { "value": "Africa/Cairo", "label": "(GMT+03) Cairo, Egypt" },
    { "value": "Europe/Bucharest", "label": "(GMT+03) Bucharest, Romania" },
    { "value": "Europe/Moscow", "label": "(GMT+03) Moscow, Russia" },
    { "value": "Asia/Dubai", "label": "(GMT+04) Dubai, United Arab Emirates" },
    { "value": "Asia/Kolkata", "label": "(GMT+05:30) Kolkata, India" },
    { "value": "Asia/Bangkok", "label": "(GMT+07) Hanoi, Vietnam" },
    { "value": "Asia/Jakarta", "label": "(GMT+07) Jakarta, Indonesia" },
    { "value": "Asia/Hong_Kong", "label": "(GMT+08) Hong Kong" },
    { "value": "Asia/Shanghai", "label": "(GMT+08) Shanghai, China" },
    { "value": "Asia/Singapore", "label": "(GMT+08) Singapore" },
    { "value": "Asia/Seoul", "label": "(GMT+09) Seoul, South Korea" },
    { "value": "Asia/Tokyo", "label": "(GMT+09) Tokyo, Japan" },
    { "value": "Australia/Sydney", "label": "(GMT+11) Sydney, Australia" },
    { "value": "Pacific/Auckland", "label": "(GMT+13) Auckland, New Zealand" },
    { "value": "Pacific/Fiji", "label": "(GMT+12) Suva, Fiji" },
    { "value": "Pacific/Chatham", "label": "(GMT+13:45) Chatham Islands, New Zealand" },,
    { "value": "Pacific/Tongatapu", "label": "(GMT+13) Nuku'alofa, Tonga" },
    { "value": "Pacific/Apia", "label": "(GMT+13) Apia, Samoa" },
]